version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: bank_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # JWT секрет
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:

